### ISSUE TITLE
C# Support

### ISSUE THREAD

**Issue by Renari** [dandeliondino/terrain-autotiler#44]
Using this via C# has not been very pleasant.

```csharp
// instantiate base tilemap
private TileMap _tileMap = GD.Load<PackedScene>("res://tilemaps/grassland/Grassland.tscn").Instantiate<TileMap>();

GDScript autoTiler = (GDScript)GD.Load("res://addons/terrain_autotiler/core/autotiler.gd");
GodotObject _autoTiler = (GodotObject)autoTiler.New(_tileMap);
```

Is what the Godot docs seem to list as the intended way to do this, but following this with something like:
```chsarp
_autoTiler.CallDeferred("set_cells_terrain_connect", 0, grassTiles, (int)Terrains.Grass, 0, false);
```
Doesn't seem to draw anything, so I've been trying to figure out where the interoperability has broken down.

**Comment by dandeliondino** [comment]
Thanks for the report. I haven't tested it with C#, so I'm not sure where the problem is. What kind of variable is grassTiles? Looking at the docs, it looks like it can't be passed directly as an array (https://docs.godotengine.org/en/stable/tutorials/scripting/cross_language_scripting.html). But there may be other compatibility problems. If anyone is more familiar with this, please let me know and I can add a note to the readme.

Specific C# support isn't on the current roadmap for the project. So, if Terrain Autotiler isn't compatible, you might want to check out Better Terrain since I believe it's been tested to work with C#.(https://github.com/Portponky/better-terrain)

**Comment by Renari** [comment]
> What kind of variable is grassTiles?
`Godot.Collections.Array<Vector2I>`, oddly enough even though the docs say not to do this their example is doing this, and casting to an object like they suggest does not compile.

**Comment by Renari** [comment]
I ended up finding out that this wasn't getting called because the method signatures for `set_cells_terrain_connect` in autotiler and tilemap are not the same, specifically autotiler does not have the option to ignore empty tiles as the last parameter.
