### ISSUE TITLE
Generation is extremely slow

### ISSUE THREAD

**Issue by Renari** [dandeliondino/terrain-autotiler#45]
I'll start off by saying I'm not sure this is something that can be fixed, and give an example of what I'm doing.

```csharp
// generate the rest of the map in the background
var halfMap = MapSize / 2;
var chunkCount = MapSize / ChunkSize;
for (var x = 0; x < chunkCount; x++)
{
	for (var y = 0; y < chunkCount; y++)
	{
		GenerateArea(new Vector2I(-halfMap + x * ChunkSize, -halfMap + y * ChunkSize), ChunkSize);
	}
}
```
In the following examples `MapSize` is set to 512 and `ChunkSize` is set to 8. In this first example I am calling;

```csharp
_tileMap.CallDeferred("set_cells_terrain_connect", 0, grassTiles, (int)Terrains.Grass, 0, false);
````
https://github.com/dandeliondino/terrain-autotiler/assets/1839179/fb014739-b9ed-43e3-94b8-f6db001a8f2a

I do have vsync on here at 165hz, as you can see performance remains reasonable. However you can also see the odd tiles because of Godot's tilemap implementation.

-------
```csharp
_autoTiler.CallDeferred("set_cells_terrain_connect", 0, grassTiles, (int)Terrains.Grass, 0);
````
https://github.com/dandeliondino/terrain-autotiler/assets/1839179/a2526508-5088-416f-8184-bb6c63dfd6d0

This is the same call using autoTiler, as you can see performance has degraded significantly, and performance continues to drop as generation continues, I was getting ~8FPS near the end of this generation.

**Comment by dandeliondino** [comment]
Yes, this plugin is slow and I don't have plans to change that. Optimizing the current algorithm in GDScript would require either changing the code in ways that would be difficult to maintain (using dictionaries and arrays instead of objects) or using multithreading (which would break some of the accuracy of the algorithm). Porting it to C++ (as a GDExtension) or even C# may improve performance significantly. I don't have any plans to do so, but perhaps someone might be interested in forking it. However, a more accurate matching algorithm should really be part of the main engine where it can take advantage of all the optimizations available there (proposal here: https://github.com/godotengine/godot-proposals/issues/7670), and then this plugin would no longer be needed.

One future feature that is planned is to provide a thread-safe function to execute the matching algorithm and return the resulting tiles, which could afterwards be applied to the TileMap. This would not improve the speed, but it would allow it to execute in the background.
